---
- name: Cisco Device
  hosts: hosts
  gather_facts: no
  tasks:
   - name: Rus Show Command
     ios_command:
       commands:
         - show ip arp
     register: ssh_output
     ignore_errors: True

   - name: ssh_output asve
     copy:
       content: "{{ ssh_output.stdout[0] }}"
       dest: "/etc/ansible/cisco/korea/arp/L3/{{ ansible_host }}.txt"
     ignore_errors: True

   - name: Assemble from fragments from a directory
     assemble:
       src: "/etc/ansible/cisco/korea/arp/L3"
       dest: "/etc/ansible/cisco/korea/arp/arp_info.txt"
     ignore_errors: True

   - name: Parsing the file
     shell: "cat /etc/ansible/cisco/korea/arp/arp_info.txt | sed -e '/Protocol/d' | sed -e '/show/d' | sed -e '/YR_L3S/d'  | awk '{print $2, $4, $7}'"
     register: arp_info
     ignore_errors: True

   - name: Save ARP Summary
     copy:
       content="{{ arp_info.stdout }}"
       dest="/etc/ansible/cisco/korea/arp/arp_summary.csv"
     ignore_errors: True
  tags:
   - l3_arp

